_default:
    @just --list

all:
    just android
    just ios

android:
    just android-native-sync

ios:
    just ios-native-sync

android-native-sync:
    # Build Android Native Sync SBoM
    cargo run -- ../../sbom/android-native-sync.sbom

ios-native-sync:
    # Build iOS Sync SBoM
    cargo run -- ../../sbom/ios-native-sync.sbom
