_default:
    @just --list

all:
    just android
    just ios

android:
    just android-sync

ios:
    just ios-sync

android-sync:
    # Build Android Native Sync SBoM
    cargo run -- ../../sbom/android-sync.sbom

ios-sync:
    # Build iOS Sync SBoM
    cargo run -- ../../sbom/ios-sync.sbom
